### ISSUE TITLE
Lecture 12 checklist

### ISSUE THREAD

**Issue by Aaetpio** [Neobyte01/SoftwareDevelopmentGroup2#71]
- [x] Create an issue titled "Lecture 12 checklist" to track these checklist items
- [x] Project has a software license
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work

**Comment by Aaetpio** [comment]
Forgot to close this when it was completed, closing it now.

**Comment by rudymatela** [comment]
The checklist items seem to be complete.  :-)  Good job!
